Update 23-environment-deploy.yml

diff --git a/.github/workflows/23-environment-deploy.yml b/.github/workflows/23-environment-deploy.yml
--- a/.github/workflows/23-environment-deploy.yml
+++ b/.github/workflows/23-environment-deploy.yml
@@ -18,7 +18,8 @@ jobs:
     steps:
       - name: Test
         run: |
-          echo "Tests passed"
+          echo "Tests failed"
+          exit 1
 
   deploy:
     needs: [build, test]
